name: Analyze code

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
